### ISSUE TITLE
Opens 2 Minecraft windows upon launch

### ISSUE THREAD

**Issue by MrCatguy** [olauncher/olauncher#93] opened 2024-08-06 11:17 UTC
When I launch the game it opens 2 minecraft windows, I see them for a split second and then it hides 1 of them. One of them is called Java(TM) Platform SE binary and the one my game is on is called OpenJDK Platform binary. They seem to NOT be connected (ending the 1st task in task manager does not close my game, but ending the 2nd task does close the game since well, it's what the game is running on).

It uses about 1GB of memory which is why I want to know a way to get rid of it since it's annoying to end it in task manager each time.

This doesn't happen with the defualt Minecraft launcher.

Thanks

**Comment by bigfoot547** [comment] 2024-08-06 18:29
When the launcher runs the game, it just hides itself so it can reopen if the game crashes. You can modify this behavior by editing the profile that you are launching.

**Comment by bigfoot547** [comment] 2024-08-06 18:32
Closing since this is intended behavior.

**Closed by bigfoot547** 2024-08-06 18:32 UTC
