### ISSUE TITLE
Support scaling using Wayland on Linux

### ISSUE THREAD

**Issue by codenyte** [olauncher/olauncher#49] opened 2023-12-13 00:56 UTC
Currently, the launcher doesn't scale correctly when fractional scaling on Wayland is enabled. Scaling on Xorg seems to work fine, but Xorg doesn't have support for fractional scaling (125%, 150%, etc.) which is very annoying, especially on small, high-resolution (e.g. UHD) displays.

**Comment by bigfoot547** [comment] 2023-12-13 04:52
It seems like you are using a JVM with one of those swing implementations that calls itself "DPI-aware" then acts unaware of DPI. Try a different (newer?) JVM perhaps.

**Comment by bigfoot547** [comment] 2023-12-13 18:17
Have you tried [scaling using JVM arguments](https://wiki.archlinux.org/title/HiDPI#AWT/Swing)? I do not think swing really has any API for scaling or anything. It's a pretty inflexible system.

**Comment by bigfoot547** [comment] 2023-12-13 23:33
> I think swing is simply broken on Wayland.

I can't say I'm surprised. I'll close the issue until it becomes clear that the issue is NOT upstream of the launcher (i.e. not some swing or wayland issue).

**Closed by bigfoot547** 2023-12-13 23:33 UTC
